# 配置server
server:
  port: 8088

# 配置mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mysql_crash_course?useUnicode=true&characterEncoding=UTF-8&useSSL=false

# 配置mybatis
mybatis:
  config-location: classpath:mybatis/config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml

# 配置数据源，默认使用hikari数据源